export const GET_LIST_TASKS = 'GET_LIST_TASKS';
export const GET_LIST_TASKS_REQUEST = 'GET_LIST_TASKS/pending';
export const GET_LIST_TASKS_SUCCEES = 'GET_LIST_TASKS/fulfilled';
export const GET_LIST_TASKS_FAILURE = 'GET_LIST_TASKS/rejected';

export const ADD_LIST_TASKS = 'ADD_LIST_TASKS';
export const ADD_LIST_TASKS_REQUEST = 'ADD_LIST_TASKS/pending';
export const ADD_LIST_TASKS_SUCCEES = 'ADD_LIST_TASKS/fulfilled';
export const ADD_LIST_TASKS_FAILURE = 'ADD_LIST_TASKS/rejected';

export const UPDATE_LIST_TASK = 'UPDATE_LIST_TASK';
export const UPDATE_LIST_TASK_REQUEST = 'UPDATE_LIST_TASK/pending';
export const UPDATE_LIST_TASK_SUCCEES = 'UPDATE_LIST_TASK/fulfilled';
export const UPDATE_LIST_TASK_FAILURE = 'UPDATE_LIST_TASK/rejected';

export const DELETE_LIST_TASK = 'DELETE_LIST_TASK';
export const DELETE_LIST_TASK_REQUEST = 'DELETE_LIST_TASK/pending';
export const DELETE_LIST_TASK_SUCCEES = 'DELETE_LIST_TASK/fulfilled';
export const DELETE_LIST_TASK_FAILURE = 'DELETE_LIST_TASK/rejected';

export const REORDER_LIST_TASKS = 'REORDER_LIST_TASKS';
export const REORDER_LIST_TASKS_REQUEST = 'REORDER_LIST_TASKS/pending';
export const REORDER_LIST_TASKS_SUCCESS = 'REORDER_LIST_TASKS/fulfilled';
export const REORDER_LIST_TASKS_FAILURE = 'REORDER_LIST_TASKS/failed';

export const DELETE_CHECKED_LIST_TASK = 'DELETE_CHECKED_LIST_TASK';
export const DELETE_CHECKED_LIST_TASK_REQUEST = 'DELETE_CHECKED_LIST_TASK/pending';
export const DELETE_CHECKED_LIST_TASK_SUCCEES = 'DELETE_CHECKED_LIST_TASK/fulfilled';
export const DELETE_CHECKED_LIST_TASK_FAILURE = 'DELETE_CHECKED_LIST_TASK/rejected';
